CREATE DATABASE IF NOT EXISTS Abertura_de_chamado;
USE Abertura_de_chamado;
-- ============================================================
----- AS TABELAS
-- ============================================================
-- Adicione isso antes do CREATE para garantir que a tabela seja recriada do zero
DROP TABLE IF EXISTS tb_USUARIO;
DROP TABLE IF EXISTS tb_CHAMADO; 
DROP TABLE IF EXISTS tb_DEPARTAMENTO;



CREATE TABLE IF NOT EXISTS tb_CHAM_HISTORICO(
ID_CHAM_HISTORICO SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
FK_ID_CHAMADO INT,
FK_ID_HISTORICO INT
);

CREATE TABLE IF NOT EXISTS tb_CHAMADO(
ID_CHAMADO SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
LOCAL_CHAMADO VARCHAR (50) NOT NULL,
DESCRICAO VARCHAR (50) NOT NULL,
PRIORIDADE VARCHAR (50) NOT NULL,
STATUS_CHAMADO VARCHAR (50) NOT NULL,
DATA_ABERTURA DATE NOT NULL,
FK_ID_USUARIO INT NOT NULL,
FK_ID_TECNICO INT NOT NULL,
FK_ID_DEPARTAMENTO INT NOT NULL,
FK_ID_EQUIPAMENTO INT
);

CREATE TABLE IF NOT EXISTS tb_HISTORICO(
ID_HISTORICO SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
DATA_IN_CHAMADO DATE NOT NULL,
DATA_FI_CHAMADO DATE NOT NULL,
LOCAL_CHAMADO VARCHAR (50) NOT NULL,
STATUS_CHAMADO VARCHAR (50) NOT NULL,
FK_ID_CHAMADO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_EQUIPAMENTO(
ID_EQUIPAMENTO SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_EQUIPAMENTO VARCHAR(50) NOT NULL,
FK_ID_CHAMADO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_USUARIO(
ID_USUARIO SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_USUARIO VARCHAR(50) NOT NULL,
EMAIL_USUARIO VARCHAR (50) NOT NULL,
CARGO VARCHAR (50) NOT NULL,
FK_ID_DEPARTAMENTO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_DEPARTAMENTO(
ID_DEPARTAMENTO SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_DEPARTAMENTO VARCHAR (50) NOT NULL,
FK_ID_CHAMADO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_TECNICO(
ID_TECNICO SMALLINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_TECNICO VARCHAR (50) NOT NULL,
FUNCAO_TECNICO VARCHAR (50) NOT NULL,
FK_ID_DEPARTAMENTO INT NOT NULL
);

-- ========================================================================================
-- OS INSERTS
-- ========================================================================================
-- 1. INSERTS NAS TABELAS DE BASE (DEPARTAMENTO, USUARIO, TECNICO, EQUIPAMENTO)
INSERT INTO tb_DEPARTAMENTO (NOME_DEPARTAMENTO, FK_ID_CHAMADO) VALUES ('TI', 0), ('RH', 0), ('Financeiro', 0);

INSERT INTO tb_USUARIO (NOME_USUARIO, EMAIL_USUARIO, CARGO, FK_ID_DEPARTAMENTO) 
VALUES ('Carlos Andrade', 'carlos@email.com', 'Analista', 1), ('Julia Costa', 'julia@email.com', 'Gerente', 2);

INSERT INTO tb_TECNICO (NOME_TECNICO, FUNCAO_TECNICO, FK_ID_DEPARTAMENTO) 
VALUES ('Ricardo Tech', 'Suporte N2', 1), ('Fernanda Silva', 'Redes', 1);

INSERT INTO tb_EQUIPAMENTO (NOME_EQUIPAMENTO, FK_ID_CHAMADO) 
VALUES ('Notebook Dell XPS', 0), ('Impressora HP Laser', 0);

-- 2. INSERTS NA TABELA CHAMADO (Depende dos IDs acima)
INSERT INTO tb_CHAMADO (LOCAL_CHAMADO, DESCRICAO, PRIORIDADE, STATUS_CHAMADO, DATA_ABERTURA, FK_ID_USUARIO, FK_ID_TECNICO, FK_ID_DEPARTAMENTO, FK_ID_EQUIPAMENTO)
VALUES ('Sala de Reunião', 'Wifi não conecta', 'Alta', 'Aberto', '2023-11-01', 1, 1, 1, 1);

INSERT INTO tb_CHAMADO (LOCAL_CHAMADO, DESCRICAO, PRIORIDADE, STATUS_CHAMADO, DATA_ABERTURA, FK_ID_USUARIO, FK_ID_TECNICO, FK_ID_DEPARTAMENTO, FK_ID_EQUIPAMENTO)
VALUES ('Setor RH', 'Impressora travada', 'Média', 'Em Atendimento', '2023-11-02', 2, 2, 2, 2);

-- 3. INSERTS NA TABELA HISTORICO
INSERT INTO tb_HISTORICO (DATA_IN_CHAMADO, DATA_FI_CHAMADO, LOCAL_CHAMADO, STATUS_CHAMADO, FK_ID_CHAMADO)
VALUES ('2023-11-01', '2023-11-01', 'Sala de Reunião', 'Aberto', 1);

INSERT INTO tb_HISTORICO (DATA_IN_CHAMADO, DATA_FI_CHAMADO, LOCAL_CHAMADO, STATUS_CHAMADO, FK_ID_CHAMADO)
VALUES ('2023-11-02', '2023-11-02', 'Setor RH', 'Em Atendimento', 2);

-- 4. INSERTS NA TABELA ASSOCIATIVA (CHAM_HISTORICO)
INSERT INTO tb_CHAM_HISTORICO (FK_ID_CHAMADO, FK_ID_HISTORICO) VALUES (1, 1);
INSERT INTO tb_CHAM_HISTORICO (FK_ID_CHAMADO, FK_ID_HISTORICO) VALUES (2, 2);

-- Historicos (Como DATA_FI_CHAMADO é obrigatória no seu código, passei datas iguais para o teste)
INSERT INTO tb_HISTORICO (DATA_IN_CHAMADO, DATA_FI_CHAMADO, LOCAL_CHAMADO, STATUS_CHAMADO, FK_ID_CHAMADO)
VALUES ('2023-11-01', '2023-11-01', 'TI', 'Aberto', 1);
INSERT INTO tb_HISTORICO (DATA_IN_CHAMADO, DATA_FI_CHAMADO, LOCAL_CHAMADO, STATUS_CHAMADO, FK_ID_CHAMADO)
VALUES ('2023-11-02', '2023-11-03', 'RH', 'Fechado', 2);

-- ======================================
--       UPDATE
-- ======================================

UPDATE tb_DEPARTAMENTO 
SET FK_ID_CHAMADO = 1 
WHERE ID_DEPARTAMENTO = 1;

-- ==========================================
-- SELECT COMPLETO (RELATÓRIO DE CHAMADOS)
-- ==========================================
SELECT 
    C.ID_CHAMADO AS 'Chamado nº',
    C.DATA_ABERTURA AS 'Data',
    U.NOME_USUARIO AS 'Solicitante',
    C.DESCRICAO AS 'Descrição',
    T.NOME_TECNICO AS 'Técnico Responsável',
    D.NOME_DEPARTAMENTO AS 'Departamento',
    E.NOME_EQUIPAMENTO AS 'Equipamento',
    C.STATUS_CHAMADO AS 'Status'
FROM tb_CHAMADO C
JOIN tb_USUARIO U ON C.FK_ID_USUARIO = U.ID_USUARIO
JOIN tb_TECNICO T ON C.FK_ID_TECNICO = T.ID_TECNICO
JOIN tb_DEPARTAMENTO D ON C.FK_ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
LEFT JOIN tb_EQUIPAMENTO E ON C.FK_ID_EQUIPAMENTO = E.ID_EQUIPAMENTO;


-- Ver tabela de Historico conforme os requisitos que você pediu
SELECT 
    ID_HISTORICO, 
    DATA_IN_CHAMADO, 
    DATA_FI_CHAMADO, 
    LOCAL_CHAMADO, 
    STATUS_CHAMADO, 
    FK_ID_CHAMADO AS 'ID CHAMADO' 
FROM tb_HISTORICO;

SELECT 
    ID_USUARIO,
    NOME_USUARIO,
    EMAIL_USUARIO,
    CARGO,
    FK_ID_DEPARTAMENTO AS 'ID DEPARTAMENTO'
    FROM tb_USUARIO;
    
    SELECT 
    ID_DEPARTAMENTO "ID DEPARTAMENTO",
    NOME_DEPARTAMENTO,
    FK_ID_CHAMADO AS "ID CHAMADO"
    FROM tb_DEPARTAMENTO;
    

